### ISSUE TITLE
Probleme mit JavaFX auf Java 11

### ISSUE THREAD

**Issue by Makkarov** [ptrckbnck/SQLChecker#1]
Guten Tag,

ich als Mac User habe die neuste Version von Java runtergeladen Java 11 und beim Starten des Programms über das Terminal, kriege ich folgende Fehlermeldung. Da ich mich nicht gar nicht mit Java auskenne, wäre ich froh über eine mögliche Lösung dieses Problems. Laut de Fehlermeldung scheint es Grafikprobleme zu geben. Müssen womöglich zusätzlich libaries installiert werden?

Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Phate94** [comment]
Dieses Problem ist nicht Mac-spezifisch!
Ich habe eine sehr ähnliche Fehlermeldung (s.u.) auf zwei verschiedenen Windows(10)-Rechnern erhalten. Auf beiden Rechnern wurde das aktuelle JDK 11 installiert (das es keine JRE 11 gibt) und die nötige PATH-Variable gesetzt. Die Meldung war bei beiden Rechnern identisch.

Unter Linux (Ubuntu 18.04) ließ sich der SQLChecker problemlos starten.

[...]>java -jar SQLChecker-1.0.jar
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by enigma-a** [comment]
Moin, es besteht die Möglichkeit die fehlenden jmods nach zu laden.
Dies führt bei mir allerdings zum nächsten Problem:

GLFactory.static - Platform: Mac OS X - not available: com.sun.prism.es2.MacGLFactory
java.lang.ClassNotFoundException: com.sun.prism.es2.MacGLFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.es2.GLFactory$FactoryLoader.run(GLFactory.java:108)
	at com.sun.prism.es2.GLFactory$FactoryLoader.run(GLFactory.java:100)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.prism.es2.GLFactory.<clinit>(GLFactory.java:97)
	at com.sun.prism.es2.ES2Pipeline.<clinit>(ES2Pipeline.java:76)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:187)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.ClassNotFoundException: com.sun.glass.ui.mac.MacPlatformFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.sun.glass.ui.PlatformFactory.getPlatformFactory(PlatformFactory.java:42)
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)
Failed to load Glass factory class
Exception in thread "main" java.lang.NullPointerException
	at com.sun.glass.ui.Application.run(Application.java:144)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:258)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:269)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:834)

ich werde es später mal mit einer vm ausprobieren ggf. liegt der Fehler in meiner Config.

**Comment by ghost** [comment]
So nach langem hin und her. :-)
Unter java 11 sind die javafx verschwunden, diese können zwar nachgeladen werden allerdings kommen dann Fehler über fehlende Klassen.
Zur Lösung "MacOS":
Ich hab einfach Java 10.0.2 installiert :-) und natürlich 11 wieder gelöscht.

**Comment by Makkarov** [comment]
Dankeschön @enigma-a es funktioniert wirklich mit 10.0.2  :)

**Comment by ptrckbnck** [comment]
Mit Java 10 sollte es keine Probleme geben, da Javafx noch integriert ist. Im Zweifelsfall also immer Java 10 verwenden. Ich werde mich darum kümmern, dass es auch unter 11 reibungslos läuft.

**Comment by donnerluetjen** [comment]
Hab Java 11 und Java 8 deinstalliert, dann JRE 10 installiert. Läuft aber ohne JDK nicht.
<img width="945" alt="bildschirmfoto 2018-11-06 um 09 59 10" src="https://user-images.githubusercontent.com/20632/48053331-b90b1000-e1aa-11e8-8061-400cf04df53b.png">

**Comment by ptrckbnck** [comment]
Deinem Screenshot zufolge findet er die JRE nicht. Schau mal auf was "java" verlinkt.

~~Ich habe eine neue Version im Branch javafx erstellt. Die jar gibt es hier: https://github.com/ptrckbnck/SQLChecker/blob/javafx/SQLChecker-1.0.1.jar . Diese benutzt JavaFX 11. Also brauchst du Java JRE 11. Sag mr bitte, ob diese Jar bei dir funktioniert. Ich kann das Problem leider nicht bei mir replizieren.~~

Der neue Release 1.0.2 sollte diesen Bug beheben. Ich bitte um Rückmeldung.

**Comment by Fl4mer** [comment]
Hi, 1.0.2 funktioniert nun mit Java JRE 11 auf Mac. Habe jedoch folgenden Error, wenn ich meinen SQL-Server damit verbinden möchte und eine Aufgabe ausführe.

`> 1a: SQL Code wird ausgeführt.
> [ERROR] Wed Nov 07 14:32:23 CET 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> [ERROR] Wed Nov 07 14:32:23 CET 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> Query OK, 1 Spalten wurden verändert.
> [ERROR] Wed Nov 07 14:32:23 CET 2018 WARN: Caught while disconnecting...
> [ERROR] 
> [ERROR] EXCEPTION STACK TRACE:
> [ERROR] 
> [ERROR] 
> [ERROR] 
> [ERROR] ** BEGIN NESTED EXCEPTION ** 
> [ERROR] 
> [ERROR] javax.net.ssl.SSLException
> [ERROR] MESSAGE: closing inbound before receiving peer's close_notify
> [ERROR] 
> [ERROR] STACKTRACE:
> [ERROR] 
> [ERROR] javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
> [ERROR] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
> [ERROR] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
> [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
> [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
> [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
> [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:645)
> [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:624)
> [ERROR] 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
> [ERROR] 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
> [ERROR] 	at de.unifrankfurt.dbis.GUI.SQLRunner.call(SQLRunner.java:79)
> [ERROR] 	at de.unifrankfurt.dbis.GUI.SQLRunner.call(SQLRunner.java:16)
> [ERROR] 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
> [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
> [ERROR] 
> [ERROR] 
> [ERROR] ** END NESTED EXCEPTION **
> [ERROR] 
> [ERROR] `

**Comment by dheckl** [comment]
Als Workaround bis ein Fix zur Verfügung steht bietet sich die serverseitige Deaktivierung von SSL und die Anpassung des standardmäßig genutzten Authentifizierungsverfahrens an.

**my.cnf**
```
[mysqld]
skip_ssl
default-authentication-plugin=mysql_native_password
```

**Comment by ptrckbnck** [comment]
Hallo @Fl4mer, danke für deine Rückmeldung. Ich habe für deinen Report ein neues Issue geöffnet. Wenn Javafx jetzt funktioniert, schließe ich diesen Issue.
@dheckl danke für den Hinweis. Ich werde die Authentifizierung anpassen.
