### ISSUE TITLE
ssl problem

### ISSUE THREAD

**Issue by ptrckbnck** [ptrckbnck/SQLChecker#3]
Hi, 1.0.2 funktioniert nun mit Java JRE 11 auf Mac. Habe jedoch folgenden Error, wenn ich meinen SQL-Server damit verbinden möchte und eine Aufgabe ausführe.
`> 1a: SQL Code wird ausgeführt.
> [ERROR] Wed Nov 07 14:32:23 CET 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> [ERROR] Wed Nov 07 14:32:23 CET 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> Query OK, 1 Spalten wurden verändert.
> [ERROR] Wed Nov 07 14:32:23 CET 2018 WARN: Caught while disconnecting...
> [ERROR] 
> [ERROR] EXCEPTION STACK TRACE:
> [ERROR] 
> [ERROR] 
> [ERROR] 
> [ERROR] ** BEGIN NESTED EXCEPTION ** 
> [ERROR] 
> [ERROR] javax.net.ssl.SSLException
> [ERROR] MESSAGE: closing inbound before receiving peer's close_notify
> [ERROR] 
> [ERROR] STACKTRACE:
> [ERROR] 
> [ERROR] javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
> [ERROR] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
> [ERROR] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
> [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
> [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
> [ERROR] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
> [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:645)
> [ERROR] 	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:624)
> [ERROR] 	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1313)
> [ERROR] 	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1743)
> [ERROR] 	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:717)
> [ERROR] 	at de.unifrankfurt.dbis.GUI.SQLRunner.call(SQLRunner.java:79)
> [ERROR] 	at de.unifrankfurt.dbis.GUI.SQLRunner.call(SQLRunner.java:16)
> [ERROR] 	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
> [ERROR] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> [ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
> [ERROR] 
> [ERROR] 
> [ERROR] ** END NESTED EXCEPTION **
> [ERROR] 
> [ERROR] `

_Originally posted by @Fl4mer in https://github.com/ptrckbnck/SQLChecker/issues/1#issuecomment-436626726_

**Comment by ptrckbnck** [comment]
Ist mit Version 1.0.3 (https://github.com/ptrckbnck/SQLChecker/releases/tag/v1.0.3) behoben.
